"""
PDF Report Generator for GR&R studies.

Uses ReportLab to produce a professional, multi-page PDF containing:
  - Study metadata (date, operators, gauge, part numbers)
  - ANOVA / Xbar-R results table
  - Variance component breakdown chart
  - Acceptance verdict with color-coded status
  - Appendix with raw data
"""

from __future__ import annotations

import logging
from datetime import datetime
from io import BytesIO
from typing import Any

from grr.acceptance import AcceptanceLevel, AcceptanceVerdict
from grr.calculator import GRRResult

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
)
from reportlab.graphics.shapes import Drawing
from reportlab.graphics.charts.barcharts import VerticalBarChart

logger = logging.getLogger(__name__)


def create_pdf(
    result: GRRResult,
    verdict: AcceptanceVerdict,
    *,
    study_metadata: dict[str, Any] | None = None,
    title: str = "GR&R Study Report",
) -> bytes:
    """
    Generate a PDF report for a completed GR&R study.

    Parameters
    ----------
    result : GRRResult
        Calculated GR&R metrics.
    verdict : AcceptanceVerdict
        Pass / conditional / fail classification.
    study_metadata : dict | None
        Optional metadata (study date, gauge ID, etc.).
    title : str
        Report title.

    Returns
    -------
    bytes
        Raw PDF content.
    """
    logger.info("Generating PDF report...")
    if study_metadata is None:
        study_metadata = {}

    buffer = BytesIO()

    def on_page(canvas, doc):
        canvas.saveState()
        canvas.setFont('Helvetica', 9)
        canvas.setFillColor(colors.gray)
        canvas.drawString(inch, 0.5 * inch, "Generated by Arad Quality Agent | Confidential")
        canvas.restoreState()

    doc = SimpleDocTemplate(
        buffer, pagesize=letter, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=72
    )
    story = []
    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        'TitleStyle', parent=styles['Heading1'], fontSize=18, fontName='Helvetica-Bold'
    )
    subtitle_style = ParagraphStyle(
        'SubtitleStyle', parent=styles['Normal'], fontSize=12, textColor=colors.gray
    )
    verdict_text_style = ParagraphStyle(
        'VerdictText', parent=styles['Normal'], fontSize=12, textColor=colors.black, alignment=1
    )
    verdict_title_style = ParagraphStyle(
        'VerdictTitle', parent=styles['Heading2'], fontSize=16, fontName='Helvetica-Bold', textColor=colors.black, alignment=1
    )

    # 1. Header Section
    story.append(Paragraph(title, title_style))
    story.append(Paragraph("Gauge Repeatability & Reproducibility Analysis", subtitle_style))
    story.append(Spacer(1, 10))
    # Horizontal line separator
    story.append(Table([['']], colWidths=['100%'], style=[('LINEABOVE', (0, 0), (-1, -1), 1, colors.black)]))
    story.append(Spacer(1, 10))

    # Metadata Table
    md_left = [
        ["Study Date:", study_metadata.get("Study Date", "N/A")],
        ["Equipment ID:", study_metadata.get("Equipment ID", "N/A")],
        ["Characteristic:", study_metadata.get("Characteristic", "N/A")],
        ["Method:", study_metadata.get("Method", "N/A")]
    ]
    md_right = [
        ["Operators:", str(study_metadata.get("Operators", "N/A"))],
        ["Parts:", str(study_metadata.get("Parts", "N/A"))],
        ["Trials:", str(study_metadata.get("Trials", "N/A"))],
        ["Generated By:", str(study_metadata.get("Generated By", "N/A"))]
    ]
    md_data = [md_left[i] + md_right[i] for i in range(4)]

    md_table = Table(md_data, colWidths=[1.2 * inch, 1.5 * inch, 1.2 * inch, 1.5 * inch])
    md_table.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTNAME', (2, 0), (2, -1), 'Helvetica-Bold'),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
    ]))
    story.append(md_table)
    story.append(Spacer(1, 20))

    # 2. Results Summary Table
    def safe_pct(val: float, total: float) -> float:
        return (val / total * 100) if total > 0 else 0.0

    tv = result.total_variation
    ev_pct = safe_pct(result.repeatability, tv)
    av_pct = safe_pct(result.reproducibility, tv)
    pv_pct = safe_pct(result.part_variation, tv)

    res_data = [
        ["Component", "Value", "% Contribution"],
        ["Repeatability (EV)", f"{result.repeatability:.4f}", f"{ev_pct:.1f}%"],
        ["Reproducibility (AV)", f"{result.reproducibility:.4f}", f"{av_pct:.1f}%"],
        ["Part Variation (PV)", f"{result.part_variation:.4f}", f"{pv_pct:.1f}%"],
        ["Total Variation (TV)", f"{result.total_variation:.4f}", "100%"],
        ["GR&R %", f"{result.total_grr:.2f}%", "—"],
        ["NDC", str(result.ndc), "—"]
    ]

    res_table = Table(res_data, colWidths=[2.5 * inch, 1.5 * inch, 1.5 * inch])
    res_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.lightgrey),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('ALIGN', (0, 0), (0, -1), 'LEFT'),
        ('ALIGN', (1, 0), (-1, -1), 'RIGHT'),
        ('INNERGRID', (0, 0), (-1, -1), 0.25, colors.black),
        ('BOX', (0, 0), (-1, -1), 0.25, colors.black),
    ]))
    for i in range(1, len(res_data)):
        if i % 2 == 0:
            res_table.setStyle(TableStyle([('BACKGROUND', (0, i), (-1, i), colors.whitesmoke)]))

    story.append(res_table)
    story.append(Spacer(1, 30))

    # 3. Acceptance Verdict Box
    if verdict.level == AcceptanceLevel.ACCEPTABLE:
        box_color = colors.lightgreen
    elif verdict.level == AcceptanceLevel.CONDITIONAL:
        box_color = colors.yellow
    else:
        box_color = colors.lightcoral

    verdict_elements = [
        Paragraph(verdict.level.value.upper().replace("_", " "), verdict_title_style),
        Spacer(1, 5)
    ]
    for r in verdict.remarks:
        verdict_elements.append(Paragraph(r, verdict_text_style))

    verdict_table = Table([[verdict_elements]], colWidths=['100%'])
    verdict_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, 0), box_color),
        ('BOX', (0, 0), (0, 0), 1, colors.black),
        ('TOPPADDING', (0, 0), (0, 0), 10),
        ('BOTTOMPADDING', (0, 0), (0, 0), 10),
        ('LEFTPADDING', (0, 0), (0, 0), 10),
        ('RIGHTPADDING', (0, 0), (0, 0), 10),
        ('ALIGN', (0, 0), (0, 0), 'CENTER'),
        ('VALIGN', (0, 0), (0, 0), 'MIDDLE'),
    ]))
    story.append(verdict_table)

    # PAGE 2
    story.append(PageBreak())

    # 4. Variance Component Bar Chart
    story.append(Paragraph("Variance Component Breakdown", styles['Heading2']))
    story.append(Spacer(1, 10))

    d = Drawing(400, 200)
    bc = VerticalBarChart()
    bc.x = 50
    bc.y = 50
    bc.height = 125
    bc.width = 300
    bc.data = [[ev_pct, av_pct, pv_pct]]
    bc.strokeColor = colors.black
    bc.valueAxis.valueMin = 0
    bc.valueAxis.valueMax = max(100, ev_pct, av_pct, pv_pct) + 10
    bc.valueAxis.valueStep = 20
    bc.categoryAxis.labels.boxAnchor = 'ne'
    bc.categoryAxis.labels.dx = 8
    bc.categoryAxis.labels.dy = -2
    bc.categoryAxis.labels.angle = 0
    bc.categoryAxis.categoryNames = ['EV%', 'AV%', 'PV%']
    bc.bars[0].fillColor = colors.steelblue

    d.add(bc)
    story.append(d)
    story.append(Spacer(1, 30))

    # 5. AIAG REFERENCE TABLE
    story.append(Paragraph("AIAG MSA Reference Guidelines", styles['Heading3']))
    story.append(Spacer(1, 10))

    ref_data = [
        ["Threshold", "Verdict", "Guideline"],
        ["< 10%", "Acceptable", "Suitable for production"],
        ["10-30%", "Conditional", "Engineering review required"],
        ["> 30%", "Not Acceptable", "Must improve before use"],
        ["NDC ≥ 5", "Adequate", "Can distinguish parts"]
    ]
    ref_table = Table(ref_data, colWidths=[1.5 * inch, 1.5 * inch, 2.5 * inch])
    ref_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.lightgrey),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('INNERGRID', (0, 0), (-1, -1), 0.25, colors.black),
        ('BOX', (0, 0), (-1, -1), 0.25, colors.black),
    ]))
    story.append(ref_table)

    doc.build(story, onFirstPage=on_page, onLaterPages=on_page)
    return buffer.getvalue()
